apps/review/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
    url(r'^dashboard$', views.dashboard),
    url(r'^add$', views.add),
    url(r'^create$', views.create),
    url(r'^remove/(?P<id>\d+)/$', views.remove),
    url(r'^delete/(?P<id>\d+)/$', views.delete),
    url(r'^wish$', views.wish),
    url(r'^item/(?P<id>\d+)/$', views.item),
    url(r'^logout$', views.logout)
]

belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
      url(r'^', include('apps.review.urls'))
  ]

apps/review/models.py
from __future__ import unicode_literals
import re
import bcrypt, datetime
from dateutil.parser import parse as parse_date
from django.db import models


class UserManager(models.Manager):
    def registration_validator(self, postData):
        errors = {}
        if len(postData['registration_name']) < 3:
            errors['registration_name'] = "Name cannot be shorter than 3 characters"

        if len(postData['registration_username']) < 3:
            errors['registration_username'] = "Username cannot be shorter than 3 characters"

        if (User.objects.filter(username=postData['registration_username']).exists()):
            errors['registration_user_exists'] = "A user with that username already exists"

        if len(postData['registration_password']) < 8:
            errors['registration_password'] = "Password is too short"

        if postData['registration_password'] != postData['confirm_password']:
            errors['confirm_password'] = "Passwords do not match"
            
        if len(postData['date_hired']) == 0:
            errors['date_hired'] = "Please enter a date"
        return errors
    
    def login_validator(self, postData):
        errors = {}
        if (User.objects.filter(username=postData['login_username']).exists()) == False:
            errors['login_false'] = "A user with that username does not exist"

        if (User.objects.filter(username=postData['login_username']).exists()):
            user = User.objects.filter(username=postData['login_username'])[0]
            if (bcrypt.checkpw(postData['login_password'].encode(), user.password.encode())) == False:
                errors['wrong_password'] = "Incorrect password"

        if len(postData['login_username']) == 0:
            errors['login_username'] = "You must enter a username"

        if len(postData['login_password']) == 0:
            errors['login_password'] = "You must enter a password"

        return errors

    def item_validator(self, postData):
        errors = {}
        if len(postData['item']) == 0:
            errors['item_empty'] = "You must enter an item"

        if len(postData['item']) < 3:
            errors['short_item'] = "Item name must be more than 3 characters"   
        return errors
    


class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    date_hired = models.DateTimeField()
    items = models.ManyToManyField('Item')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

class Item(models.Model):
    item = models.CharField(max_length=255)
    added_by = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/review/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
import bcrypt
from models import User, Item

# Display the registration and login 
def index(request):
    if 'id' in request.session:
        return redirect('/dashboard')
    return render(request, 'review/index.html')

# Register a new validated user and store their ID in session
def register(request):
    errors = User.objects.registration_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')
    hashed_password = bcrypt.hashpw(request.POST['registration_password'].encode(), bcrypt.gensalt())
    user = User.objects.create(name=request.POST['registration_name'], username=request.POST['registration_username'], date_hired=request.POST['date_hired'], password=hashed_password)
    user.save()
    request.session['id'] = user.id
    return redirect('/dashboard')

# Login a validated user and store their ID in session
def login(request):
    errors = User.objects.login_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')

    if (User.objects.filter(username=request.POST['login_username']).exists()):
        user = User.objects.filter(username=request.POST['login_username'])[0]
        if (bcrypt.checkpw(request.POST['login_password'].encode(), user.password.encode())):
            request.session['id'] = user.id
            return redirect('/dashboard')
    return redirect('/')

# Successfully registered or logged in users will be sent to a list of their trips and other plans
def dashboard(request):
    if not 'id' in request.session:
        return redirect('/')
    user = User.objects.get(id=request.session['id'])
    items = Item.objects.filter(id=user.id)
    other = Item.objects.all().exclude(user__id=user.id)
    context = {
        "user": user,
        "items": items,
        "other": other
    }
    return render(request, 'review/dashboard.html', context)

# Add other user's created trips to their own schedules
def wish(request):
    item = Item.objects.filter(id=request.POST['item_id']).first()
    user = User.objects.get(id=request.session['id'])
    user.items.add(item)
    user.save()
    return redirect('/dashboard')

# Detailed information about a specific destination
def item(request, id):
    if not 'id' in request.session:
        return redirect('/')
    item = Item.objects.get(id=id)
    context = {
        "item": item
    }
    return render(request, 'review/item.html', context)
    
# Render the app a trip page
def add(request):
    if not 'id' in request.session:
        return redirect('/')
    return render(request, 'review/add.html')

# Post a new trip into the database and return to the travels page
def create(request):
    if request.method == "GET":
        return redirect('/add')
    errors = User.objects.item_validator(request.POST)
    if len(errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/add')
    user = User.objects.get(id=request.session['id'])
    item = Item.objects.create(
        item=request.POST.get('item'),
        added_by=user
    )
    user.items.add(item)
    user.save()
    return redirect('/dashboard')

# Remove an item from a wishlist that wasn't created by the logged in user
def remove(request, id):
    item = Item.objects.get(id=id)
    user = User.objects.get(id=request.session['id'])
    user.items.remove(item)
    return redirect('/dashboard')


# Deletes items added to a wishlist created by the logged in user
def delete(request, id):
    item = Item.objects.get(id=id)
    item.delete()
    return redirect('/dashboard')

# Remove a logged in user from session and redirects to /
def logout(request):
    request.session.clear()
    return redirect('/')

apps/review/templates/review/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Item</title>
    <meta charset="utf-8"> {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'review/style.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col nav justify-content-end">
                <a href="/dashboard" class="nav-link">Home</a>
                <a href="/logout" class="nav-link">Logout</a>
            </div>
        </div>
        <div class="row justify-content-center">
            <h1 class="display-4">Create a New Wish List Item</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-4">
                <form method="POST" action="/create">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Item / Product</label>
                        <input name="item" type="text" class="form-control"> 
                        {% if messages %} 
                        {%for message in messages %} 
                        {%if "item_empty" in message.tags %}
                        <div class="form-group has-danger">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{message}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>
                        {%endif%} {%endfor%} {% endif %}
                        {% if messages %} 
                        {%for message in messages %} 
                        {%if "short_item" in message.tags %}
                        <div class="form-group has-danger">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{message}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>
                        {%endif%} {%endfor%} {% endif %}
                    </div>
                    <button class="btn btn-outline-primary float-right">Add</button>
                    </form>
            </div>
        </div>
        
    </div>
    </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>

</html>

apps/review/templates/review/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Travel Dashboard</title>
    <meta charset="utf-8"> {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'review/style.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <a href="/logout" class="nav-link text-right">Logout</a>
            </div>
        </div>
        <div class="row">
            <h1 class="display-4">Hello, {{user.username}}!</h1>
        </div>
        <div class="row item-table">
            <p class="lead">Your Wish List</p>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Date Added</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in user.items.all %}
                    <tr>
                        <td>
                            <a href="/item/{{item.id}}">
                                {{item.item}}
                            </a>
                        </td>
                        <td>{{item.added_by.username}}</td>
                        <td>{{item.created_at.date}}</td>
                        <td>
                            {% if item.added_by.username == user.username %}
                            <a class="nav-link" href="/delete/{{item.id}}">Delete</a>
                            {% else %}
                            <a class="nav-link" href="/remove/{{item.id}}">Remove from my Wishlist</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row item-table">
            <p class="lead">Other Users' Wish List</p>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Item</th>
                        <th scope="col">Added by</th>
                        <th scope="col">Date Added</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in other %}
                    <tr>
                        <form action="/wish" method="POST">
                            {% csrf_token %}
                            <input value="{{item.id}}" name="item_id" type="hidden">
                            <td>
                                <a href="/item/{{item.id}}">
                                    {{item.item}}
                                </a>
                            </td>
                            <td>{{item.added_by.username}}</td>
                            <td>{{item.created_at.date}}</td>
                            <td>
                                <input type="submit" value="Add to my wishlist" class="btn btn-outline-primary">
                            </td>
                        </form>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col">
                <a href="/add" class="nav-link text-right">Add Item</a>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>

</html>

apps/review/templates/review/index.html
<!doctype html>
<html lang="en">

<head>
    <title>Welcome</title>
    <meta charset="utf-8"> {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'review/style.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="display-4 text-center">Welcome!</h1>
            </div>
        </div>
        <div class="row justify-content-center align-items-center">
            <div class="card-deck">
                <div class="card">
                    <h4 class="card-header">Register</h4>
                    <div class="card-body">
                        <form method="POST" action="/register">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Name</label>
                                <input name="registration_name" type="text" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "registration_name" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Username</label>
                                <input name="registration_username" type="text" class="form-control"> 
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "registration_username" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "registration_user_exists" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input name="registration_password" type="password" class="form-control">
                                <small class="form-text text-muted">
                                    Password must be at least 8 characters
                                </small>
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "registration_password" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Password Confirmation</label>
                                <input name="confirm_password" type="password" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "confirm_password" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Date Hired</label>
                                <input name="date_hired" class="form-control" type="date">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "date_hired" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            <input value="Register" type="submit" class="btn btn-outline-primary float-right">
                        </form>
                    </div>
                </div>
            </div>
                <div class="card">
                    <h4 class="card-header">Login</h4>
                    <div class="card-body">
                        <form method="POST" action="/login">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Username</label>
                                <input name="login_username" type="text" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "login_false" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "login_username" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input name="login_password" type="password" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "wrong_password" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "login_password" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <input value="Login" type="submit" class="btn btn-outline-primary float-right">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>

</html>

apps/review/templates/review/item.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Item</title>
    <meta charset="utf-8"> {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'review/style.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col nav justify-content-end">
                <a href="/dashboard" class="nav-link">Home</a>
                <a href="/logout" class="nav-link">Logout</a>
            </div>
        </div>
        <div class="row">
            <h1 class="display-4">{{item.item}}</h1>
        </div>
        <div class="row">
            <div class="col">
                <p>Users who addded this product/item under their wish list</p>
                {% for user in item.user_set.all %}
                <p class="lead">{{user.name}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>

</html>